### ISSUE TITLE
Plugin active and toggle on. Stops sending requests to the server. 

### ISSUE THREAD

**Issue by mmiscool** [Autodrop3d/AD3d-octoprint-connect#2]
See log files.

[octoprint (8).log](https://github.com/Autodrop3d/AD3d-octoprint-connect/files/6330038/octoprint.8.log)
[octoprint (7).log](https://github.com/Autodrop3d/AD3d-octoprint-connect/files/6330039/octoprint.7.log)
[octoprint (6).log](https://github.com/Autodrop3d/AD3d-octoprint-connect/files/6330040/octoprint.6.log)
[octoprint (5).log](https://github.com/Autodrop3d/AD3d-octoprint-connect/files/6330041/octoprint.5.log)
[octoprint (4).log](https://github.com/Autodrop3d/AD3d-octoprint-connect/files/6330042/octoprint.4.log)
[octoprint (3).log](https://github.com/Autodrop3d/AD3d-octoprint-connect/files/6330043/octoprint.3.log)

**Comment by jneilliii** [comment]
Does this seem to be tied to canceling a print? The only time in these logs that I see the polling not running is after a print cancel event.

**Comment by jneilliii** [comment]
Actually looks like the polling continued after that PrintCancelled event too, so I don't think that's it. Can you help identify a time in which the plugin wasn't polling but was enabled to?

**Comment by mmiscool** [comment]
Seems to be corrected now.
